### ISSUE TITLE
Support for GeoSPARQL

### ISSUE THREAD

**Issue by akuckartz** [LinkedDataFragments/Client.js#10]
GeoSPARQL support would be great. The subset supported by Apache Jena probably would be enough to make this useful.

**Comment by elf-pavlik** [comment]
:+1: i wonder if it relates in any way to https://github.com/geojson/geojson-ld/issues/28

**Comment by akuckartz** [comment]
@elf-pavlik Yes, that discussion is relevant, but I think that most of the work regarding LDF does not depend on the decisions which have yet to be made there.

**Comment by akuckartz** [comment]
See the paper  [Client-side Processing of GeoSPARQL Functions with Triple Pattern Fragments](http://ceur-ws.org/Vol-1809/article-06.pdf) by Christophe Debruyne, Eamonn Clinton and Declan O’Sullivan.

They created an implementation: https://github.com/chrdebru/Client.js

Can this be integrated into the  LinkedDataFragments/Client.js ? @chrdebru

**Comment by rubensworks** [comment]
Following up in #411.
