### ISSUE TITLE
Split Triple Pattern Client / Query Engine

### ISSUE THREAD

**Issue by bergos** [LinkedDataFragments/Client.js#12]
@RubenVerborgh I'm using this package to do SPARQL queries on [RDF-Ext Stores](https://github.com/bergos/Client.js). This package may be useful for any library with a triple/quad pattern like interface to provide a SPARQL interface. But it may be useful to bundle it a little bit different:
- LinkedDataFragment client
  - query engine
  - triple pattern client

What do you think about it?

Also I would like to work on quad support. This could be also useful for LDF to access multiple LDF servers/urls in a single query using named graphs.

**Comment by RubenVerborgh** [comment]
Hi @bergos, this is certainly interesting, and has been one of our mid-term goals. Doing so will take us some time, however. (Since this activity is not core research, we have to prioritize other things).

Technically speaking, it is no problem of course: we already use dependency injection in the code, so instead of a remote Triple Pattern Fragments client, a local store can be plugged in.

**Comment by bergos** [comment]
@RubenVerborgh I added named graph support to my [fork](https://github.com/bergos/rdf-query-engine/commit/6d3e3090cb8ab7f88e5f9130144bb058eaf7cac7). I have to write some complex nested SPARQL query tests to test the edge cases, but it works already for RDF-Ext. It shouldn't break existing code. So maybe you want to merge the patch.

**Comment by RubenVerborgh** [comment]
@bergos Great to hear!

To merge this in the TPF client, we'd first need to decide how to deal with graphs. The current TPF interface does not have graphs, and there are multiple options for adding them. E.g., maybe the interface _is_ the graph, or maybe it should have a fourth element.

**Comment by elf-pavlik** [comment]
@bergos based on https://github.com/beautifulinteractions/node-quadstore/issues/50#issuecomment-334885366 it looks like Quads will land very soon https://github.com/LinkedDataFragments/Client.js/commits/feature-qpf-latest

**Comment by bergos** [comment]
I will close this issue as the requested feature is supported by the successor [Comunica](https://github.com/comunica).
