### ISSUE TITLE
Support `COUNT` queries (and aggregations in general)

### ISSUE THREAD

**Issue by ali1k** [LinkedDataFragments/Client.js#13]
Hi there,
I am trying to use the LDF client and listening to data event.
As I understood I cannot send aggregate queries like 'Count' directly. I am looking for a solution to get the total number of triples from my query. I already see it in the debugger but cannot access the value!
Could you please advise me how to get the total number of triples on client request?

p.s. I am adding support for LDF to http://ld-r.org

**Comment by mielvds** [comment]
@RubenVerborgh fyi, this count feature was also asked by @coreation for an in-house project.

**Comment by RubenVerborgh** [comment]
Hi Ali,

Basically, `COUNT` still needs to be implemented in the client, and this involves implementing aggregations. It's possible, we just haven't gotten round to it.

As @mielvds says, we also have internal incentives to do so, so this will be on the agenda in the near future.

Very intrigues by ld-r.org, great that you're adding LDF support. Keep us updated, and we'll list it at http://linkeddatafragments.org/data/.

Best,

Ruben

**Comment by ali1k** [comment]
thanks for your swift response. I am looking forward to see the support for aggregate functions on LDF-client. In the meantime, I will try to simply use the LDF server 'void:triples' with simple triple patterns.

**Comment by RubenVerborgh** [comment]
Great! Just note that `void:triples` might be approximate, so you might have to be careful.

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), where this feature is supported.
