### ISSUE TITLE
more concrete, motivating example?

### ISSUE THREAD

**Issue by dckc** [LinkedDataFragments/Client.js#14]
This linked data fragments stuff looks like an interesting approach to the federated query problem, but I'm struggling to get my head around it.

Perhaps the example in the README could be more concrete and motivating? "You can execute SPARQL queries against Triple Pattern Fragments" is not something I know I want to do until after I'm already sold. Something more concrete would be "find the number of hits in Pete Rose's baseball career" or "who won the world series in 2010?"

`http://fragments.dbpedia.org/2014/en` is a fragment of DBPedia? it looks like an address for all of DBPedia.

**Comment by dckc** [comment]
The example in [Federated SPARQL queries in your browser](http://ruben.verborgh.org/blog/2015/06/09/federated-sparql-queries-in-your-browser/) is the sort of thing I was looking for.

I'm still not quite sure I understand the protocol (I wish W3C specs used ordinary sum-of-products datatypes to specify stuff rather than all this MUST stuff. oh well).

**Comment by RubenVerborgh** [comment]
Hi @dckc, thanks for your feedback!

> This linked data fragments stuff looks like an interesting approach to the federated query problem, but I'm struggling to get my head around it.
>
> Perhaps the example in the README could be more concrete and motivating?

Glad you found the blog post, and we should probably just link it from the README (and summarize some of its points). I'll follow up our progress on that in this issue.

> "You can execute SPARQL queries against Triple Pattern Fragments" is not something I know I want to do until after I'm already sold.

Indeed. Selling the idea is what we currently try at [the website](http://linkeddatafragments.org/). The README was intended to be the technical explanation of what you can do. However, I do see a benefit of selling the idea here as well.

> http://fragments.dbpedia.org/2014/en is a fragment of DBPedia? it looks like an address for all of DBPedia.

It _is_ a fragment of DBpedia; it just happens to be the fragment of everything. At the same time, this fragment is also an entry point to more specific fragments of DBpedia.

> I'm still not quite sure I understand the protocol

The easiest way to understand the interface is to just browse fragments in your browser. For instance, [this fragment](http://fragments.dbpedia.org/2015/en?subject=http%3A%2F%2Fdbpedia.org%2Fresource%2FNikola_Tesla&predicate=&object=) shows triples which have Nikola Tesla as subject. The page itself gives you a form you can use to access other fragments.

The machine interface works the exact same way and uses the exact same IRIs. If we fetch the same URL but `Accept: application/trig`, the client will also receive a form (expressed in the [Hydra Core Vocabulary](http://www.hydra-cg.com/spec/latest/core/)) that explains what the interface does (filter by triple pattern) and how to access it.

> I wish W3C specs used ordinary sum-of-products datatypes to specify stuff rather than all this MUST stuff.

I try to keep the spec as readable as possible, but a simplifying rewrite is still pending. Suggestions to clarify the spec are [most welcome](https://github.com/HydraCG/Specifications/issues) :wink:

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), if this issue is still relevant to you, feel free to open a new issue there.
