### ISSUE TITLE
slides of #LD talk, please?

### ISSUE THREAD

**Issue by dckc** [LinkedDataFragments/Client.js#15]
I'm interested in the [ISWC2014 talk](http://videolectures.net/iswc2014_verborgh_querying_datasets/) talk, but not interested enough to sit through a video yet. I'd like to flip through the slides.

**Comment by RubenVerborgh** [comment]
Hi @dckc, you can find the slides at http://www.slideshare.net/RubenVerborgh/querying-datasets-on-the-web-with-high-availability. If you have any questions or comments, don't hesitate to ask!

**Comment by dckc** [comment]
OK thanks... I looked them over; the material there is familiar from other places and doesn't fill the gap in my understanding, though. More on that separately (perhaps as a comment on the spec)...

**Comment by RubenVerborgh** [comment]
Alright. Another possibility is the group mailing list public-linked-data-fragments@w3.org.
