### ISSUE TITLE
HTTP Proxy Support

### ISSUE THREAD

**Issue by hariharshankar** [LinkedDataFragments/Client.js#16]
Is there a way to tell the client to use an HTTP proxy? 

By default, it does not recognize either the system wide HTTP proxy settings, or the proxy set using the environment variables http_proxy, https_proxy.

**Comment by cKlee** [comment]
additional note: The [request](https://www.npmjs.com/package/request#proxies) module should take care of the environment variables. But somehow it doesn't within the client. Setting a proxy option [here](https://github.com/LinkedDataFragments/Client.js/blob/master/lib/util/HttpClient.js#L60-L67) will succeed. But setting a proxy option in a config.json will not.

Tried this:

config.json:

```json
{
  "proxy": "http://my.proxy.com:1234"
}
```

and

    ldf-client http://fragments.dbpedia.org/2014/en -f q.sparql -c config.json

**Comment by RubenVerborgh** [comment]
There is currently no support for HTTP proxies, but we can add this as a feature.

@cKlee We have [stopped using `request`](https://github.com/LinkedDataFragments/Client.js/commit/913fb5c25a0803f9cc1418c8fb38b1ea58c4a87f) because it led to socket problems.

**Comment by cKlee** [comment]
I would (still) appreciate if you add this feature.  I have no idea where to put a proxy setting. Otherwise I would make a PR, but I can't.

**Comment by RubenVerborgh** [comment]
@cKlee Would `proxychains` help you in the meantime?

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), where this feature is supported.
