### ISSUE TITLE
ldf-client-browser.js file cannot be generated

### ISSUE THREAD

**Issue by rezacsedu** [LinkedDataFragments/Client.js#19]
Hi,

While I am issuing the "**npm run browserify**" command to generate the **ldf-client-browser.js** file, I am getting a strange error that says: 

Please include the following file with any support request: npm ERR!  /var/www/html/SPARQL/npm-debug.log

Could you please provide some insights how to overcome this error? 

Thnaks, 
Reza

**Comment by RubenVerborgh** [comment]
Dear @rezacsedu,

I will need a bit more context. Can you copy the full error message? (This part is not the most relevant for us.)

Ruben

**Comment by rezacsedu** [comment]
Hi,
Here is the full error message. 

======================================
$ npm run browserify
npm ERR! Linux 3.13.0-87-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "browserify"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path /root/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/root/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
================================

**Comment by RubenVerborgh** [comment]
Did you run the command inside of the folder where you cloned the repository? The error message seems to indicate otherwise.

**Comment by rezacsedu** [comment]
Yes, I did run the command inside the cloned directory. Even, I am getting the above error therefore the ldf-client-browser.js file is not getting generated. 
Please note I followed two sources [1, 2] but getting same error messages. 

1. https://www.npmjs.com/package/ldf-client
2. https://github.com/LinkedDataFragments/jQuery-Widget.js

**Comment by RubenVerborgh** [comment]
Mmm, strange, because it is exactly the error message I get when running `npm run browserify` in a different folder.

Can you try the following steps and copy/paste the output?

```
node --version
npm --version
git clone clone https://github.com/LinkedDataFragments/Client.js.git
cd Client.js
npm install
npm run browserify
npm run browserify
```

**Comment by rezacsedu** [comment]
Hi,

I have tried the steps you mentioned and now the ldf-client-browser.js file has been generated. 
However, the problem is when I am run the project in a web--server, I am not getting list of data set and the list of example queries. 

Please refer the following image as the screenshot:
[https://github.com/rezacsedu/RDF4UV2/blob/master/LOD.png](url)

**Comment by RubenVerborgh** [comment]
> I have tried the steps you mentioned and now the ldf-client-browser.js file has been generated. 

Great to hear that!

> However, the problem is when I am run the project in a web--server

That's about [https://github.com/LinkedDataFragments/jQuery-Widget.js](jQuery-Widget) then; feel free to open an issue there. However, it most likely comes down to running `./queries-to-json.

**Comment by rezacsedu** [comment]
Hi,

You mean, do I need to execute the **queries-to-json** script?

**Comment by RubenVerborgh** [comment]
Yes.

**Comment by rezacsedu** [comment]
Well, I got the following error upon executing the command:

**-bash: ./queries-to-json: Permission denied**

I don't know why, because I am running the command as root with full privileges. Please suggest.

**Comment by RubenVerborgh** [comment]
As I explained above, this discussion really belongs in [jQuery-Widget](https://github.com/LinkedDataFragments/jQuery-Widget.js).

The error message you get is because, for some reason, `queries-to-json` isn't marked as executable on your machine (it is in the repository). `chmod +x queries-to-json` should fix it.

**Comment by rezacsedu** [comment]
Excellent. Now it's working. Thanks a million. Really appreciated.
