### ISSUE TITLE
Querying VIAF leads to errors

### ISSUE THREAD

**Issue by cKlee** [LinkedDataFragments/Client.js#20]
Got errors when querying VIAF via the browser client:

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=SELECT%20%20%3Fviaf_id%20%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%20schema%3AgivenName%20%22Larry%22%20.%0A}

**Comment by RubenVerborgh** [comment]
This is a problem on the server side: it sends invalid Turtle (likely a problem with the VIAF HDT file). However, we should handle such errors more nicely on the client as well.

**Comment by RubenVerborgh** [comment]
[This commit](https://github.com/LinkedDataFragments/jQuery-Widget.js/commit/688eb9c9238708a5e5120e708c132bca591e2dc7) already stops the flood of errors in the browser client.

**Comment by RubenVerborgh** [comment]
[This commit](https://github.com/LinkedDataFragments/Client.js/commit/6566a552bf5d84003549349854b11e61f5686329) fixes recursive parser errors being thrown.

**Comment by RubenVerborgh** [comment]
The client itself is fixed: it now deals correctly with incorrect datasources. I'll also repair the VIAF datasource such that it is valid again.
