### ISSUE TITLE
More sources leads to less results

### ISSUE THREAD

**Issue by cKlee** [LinkedDataFragments/Client.js#21]
Maybe I overlooked something here. But wit a query like

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=SELECT%20DISTINCT%20%3Fviaf_id%20%20%3Fviaf_etc%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%0A%20%20%20%20%20%20schema%3AgivenName%20%22Justitia%22%20%3B%0A%20%20%20%20%20%20%3Fp%20%3Fviaf_etc%20.%0A}

I get 28 results. As soon as I add another source the number of results decreases. Compare to

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fugent-biblio;http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=SELECT%20DISTINCT%20%3Fviaf_id%20%20%3Fviaf_etc%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%0A%20%20%20%20%20%20schema%3AgivenName%20%22Justitia%22%20%3B%0A%20%20%20%20%20%20%3Fp%20%3Fviaf_etc%20.%0A}

or

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Flov;http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=SELECT%20DISTINCT%20%3Fviaf_id%20%20%3Fviaf_etc%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%0A%20%20%20%20%20%20schema%3AgivenName%20%22Justitia%22%20%3B%0A%20%20%20%20%20%20%3Fp%20%3Fviaf_etc%20.%0A}

Or with a CONSTRUCT query compare:

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=CONSTRUCT%20{%0A%20%3Fviaf_id%20%20%3Fp%20%3Fviaf_etc%20.%0A}%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%0Aschema%3AgivenName%20%22Justitia%22%20%3B%20%20%20%20%20%20%0A%20%20%20%20%20%20%3Fp%20%3Fviaf_etc%20.%0A}

to

http://client.linkeddatafragments.org/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Flov;http%3A%2F%2Fdata.linkeddatafragments.org%2Fviaf&query=CONSTRUCT%20{%0A%20%3Fviaf_id%20%20%3Fp%20%3Fviaf_etc%20.%0A}%0AWHERE%20{%0A%20%20%20%3Fviaf_id%20%0Aschema%3AgivenName%20%22Justitia%22%20%3B%20%20%20%20%20%20%0A%20%20%20%20%20%20%3Fp%20%3Fviaf_etc%20.%0A}

**Comment by RubenVerborgh** [comment]
Good find!

Interestingly, it's non-deterministic as well: the second query gives me sometimes 23 results, and sometimes 26 (but never 28, which is correct).

I suspect this is something with event handling; perhaps the `end` event of the non-relevant datasource bubbling through.

**Comment by RubenVerborgh** [comment]
Fixed in 46df9aedaff2019dbcd21d3ae6f62389254817b0.
