### ISSUE TITLE
operators isiri, isblank and isliteral

### ISSUE THREAD

**Issue by cKlee** [LinkedDataFragments/Client.js#22]
Is there any reason why this is not implemented yet?

https://github.com/cKlee/Client.js/blob/master/lib/util/SparqlExpressionEvaluator.js#L164-L172

**Comment by RubenVerborgh** [comment]
Time ;-)

**Comment by RubenVerborgh** [comment]
Also, major rewrite of the expression engine going on behind the scenes, so no major investments are planned in the current expressions (but are welcome).

**Comment by cKlee** [comment]
So when you're rewriting pull requests to the old code is counterproductive?

**Comment by RubenVerborgh** [comment]
Didn't say that :-) Feel free to make a PR; it would need (minimal) tests though.

**Comment by cKlee** [comment]
Sure tests! I'm not familiar with the JS testing tools. How do I run this https://github.com/LinkedDataFragments/Client.js/blob/master/test/util/SparqlExpressionEvaluator-test.js ? Is it easy like http://mochajs.org/#getting-started ?

**Comment by RubenVerborgh** [comment]
Great! If you run `npm test`, everything will be tested.

To only test this specific part, do `mocha test/util/SparqlExpressionEvaluator-test.js` (after having run `npm install -g mocha`).

**Comment by cKlee** [comment]
Thanks!

**Comment by mielvds** [comment]
Careful, there is already effort on this: https://github.com/LinkedDataFragments/Client.js/tree/feature-more-filter-funtions

**Comment by cKlee** [comment]
Ah ok! No hurry. Question answered. I close this.

**Comment by RubenVerborgh** [comment]
Sorry @mielvds and @cKlee, I was aware of that branch, but not the functions that had been implemented in this. We can still merge that branch, while the rewriting effort goes on.
