### ISSUE TITLE
UnionIterator self._error undefined

### ISSUE THREAD

**Issue by cnstntn-kndrtv** [LinkedDataFragments/Client.js#33]
Hi. Im trying to use UNION operator. And found some error in 19 line in /lib/sparql/UnionIterator.js
self._error undefined.
Can you help me with this?

**Comment by RubenVerborgh** [comment]
This was a leftover from older code, updated with the new code now.

**Comment by cnstntn-kndrtv** [comment]
I created little app. And some times (some times not) i see this error. Can you please help me with this?
There is that app - https://github.com/cnstntn-kndrtv/ldf-client-test
I started to creating some ontologies (dictionaries) about russian grammar and sense of words. First is ontology-based dictionary of russian grammatical forms. http://ldf.kloud.one/ontorugrammaform. It works on linked data fragments server. 
And now im trying to create a clients for this data fragments (your jQuery-widget was an example). 
Can you please help to find the cause of error?

**Comment by RubenVerborgh** [comment]
The cause of the error was a bug, which has been fixed in 05917d99953438290d6325cd96112f4e5c31364a above.

**Comment by RubenVerborgh** [comment]
Okay then: in order to fix your code, you need to add the following to your code:

```
UnionIterator.prototype._error = function (e) { this.emit('error', e); };
```

**Comment by cnstntn-kndrtv** [comment]
Thank you
