### ISSUE TITLE
STR operator supported?

### ISSUE THREAD

**Issue by pheyvaer** [LinkedDataFragments/Client.js#35]
When executing a query with `STR` in a `FILTER` I don't get neither a response or error. The fucntions of `results.on('data')` and `results.on('end')` are never called. When trying to use `STRSTARTS` I get the error that this operator is not supported, so I guess `STR` should work then?

**Comment by pheyvaer** [comment]
Might be related to #30 ?

**Comment by mielvds** [comment]
it is

**Comment by pheyvaer** [comment]
Indeed. I tried again and noticed that it has to check > 40.000 triples. So this is why it is taking so long. Something else though, should it not `return isLiteral(a) ? literalValue(a) : '"' + a + '"';`, because `str` should return the literal value. `str("\"Ghent\"@en")` should be the same as  `str("\"Ghent\"")`, no?

**Comment by mielvds** [comment]
Yes, as is the case in the more spec-compliant https://github.com/LinkedDataFragments/Client.js/blob/feature-more-filters/lib/util/SparqlExpressionEvaluator.js#L282

**Comment by pheyvaer** [comment]
OK, I'll close this issue then as it will be resolved when merging #30.
