### ISSUE TITLE
simple query does not work with NQUADs file source

### ISSUE THREAD

**Issue by obkhan** [LinkedDataFragments/Client.js#37]
Hi,

I'm trying to get a simple query to work with NQUADS .. it does not seem to return from the client. It does seem to from a rdf triple store ??? How can I troubleshoot this and how what am I doing wrong? 

SELECT ?S ?P ?O  WHERE { ?S ?P ?O} LIMIT 3 
to return results, it

Execution log - nothing returns ... after executing
Requesting http://fragments.edmcouncil.org/fibo_1
Requesting http://fragments.edmcouncil.org/fibo_1
Requesting http://fragments.edmcouncil.org/fibo_1?page=2
Requesting http://fragments.edmcouncil.org/fibo_1?page=2
Requesting http://fragments.edmcouncil.org/fibo_1?page=3
Requesting http://fragments.edmcouncil.org/fibo_1?page=4
Requesting http://fragments.edmcouncil.org/fibo_1?page=3
Requesting http://fragments.edmcouncil.org/fibo_1?page=4
Requesting http://fragments.edmcouncil.org/fibo_1?page=5
Requesting http://fragments.edmcouncil.org/fibo_1?page=5
Requesting http://fragments.edmcouncil.org/fibo_1?page=6
Requesting http://fragments.edmcouncil.org/fibo_1?page=6
Requesting http://fragments.edmcouncil.org/fibo_1?page=7
Requesting http://fragments.edmcouncil.org/fibo_1?page=8
Requesting http://fragments.edmcouncil.org/fibo_1?page=7
Requesting http://fragments.edmcouncil.org/fibo_1?page=9
Requesting http://fragments.edmcouncil.org/fibo_1?page=8
Requesting http://fragments.edmcouncil.org/fibo_1?page=10
Requesting http://fragments.edmcouncil.org/fibo_1?page=9
Requesting http://fragments.edmcouncil.org/fibo_1?page=11
Requesting http://fragments.edmcouncil.org/fibo_1?page=10
Requesting http://fragments.edmcouncil.org/fibo_1?page=12
Requesting http://fragments.edmcouncil.org/fibo_1?page=11
Requesting http://fragments.edmcouncil.org/fibo_1?page=13
Requesting http://fragments.edmcouncil.org/fibo_1?page=12
Requesting http://fragments.edmcouncil.org/fibo_1?page=13
Requesting http://fragments.edmcouncil.org/fibo_1?page=14
Requesting http://fragments.edmcouncil.org/fibo_1?page=15
Requesting http://fragments.edmcouncil.org/fibo_1?page=14
Requesting http://fragments.edmcouncil.org/fibo_1?page=16
Requesting http://fragments.edmcouncil.org/fibo_1?page=15
Requesting http://fragments.edmcouncil.org/fibo_1?page=16
Requesting http://fragments.edmcouncil.org/fibo_1?page=17
Requesting http://fragments.edmcouncil.org/fibo_1?page=18
Requesting http://fragments.edmcouncil.org/fibo_1?page=17
Requesting http://fragments.edmcouncil.org/fibo_1?page=19
Requesting http://fragments.edmcouncil.org/fibo_1?page=18
Requesting http://fragments.edmcouncil.org/fibo_1?page=19
Requesting http://fragments.edmcouncil.org/fibo_1?page=20
Requesting http://fragments.edmcouncil.org/fibo_1?page=21
Requesting http://fragments.edmcouncil.org/fibo_1?page=20
Requesting http://fragments.edmcouncil.org/fibo_1?page=22
Requesting http://fragments.edmcouncil.org/fibo_1?page=21
Requesting http://fragments.edmcouncil.org/fibo_1?page=22
Requesting http://fragments.edmcouncil.org/fibo_1?page=23
Requesting http://fragments.edmcouncil.org/fibo_1?page=23
Requesting http://fragments.edmcouncil.org/fibo_1?page=24
Requesting http://fragments.edmcouncil.org/fibo_1?page=24
Requesting http://fragments.edmcouncil.org/fibo_1?page=25
Requesting http://fragments.edmcouncil.org/fibo_1?page=26
Requesting http://fragments.edmcouncil.org/fibo_1?page=25
Requesting http://fragments.edmcouncil.org/fibo_1?page=27
Requesting http://fragments.edmcouncil.org/fibo_1?page=26
Requesting http://fragments.edmcouncil.org/fibo_1?page=28
Requesting http://fragments.edmcouncil.org/fibo_1?page=27
Requesting http://fragments.edmcouncil.org/fibo_1?page=28
Requesting http://fragments.edmcouncil.org/fibo_1?page=29
Requesting http://fragments.edmcouncil.org/fibo_1?page=29
Requesting http://fragments.edmcouncil.org/fibo_1?page=30
Requesting http://fragments.edmcouncil.org/fibo_1?page=31
Requesting http://fragments.edmcouncil.org/fibo_1?page=30
Requesting http://fragments.edmcouncil.org/fibo_1?page=31
Requesting http://fragments.edmcouncil.org/fibo_1?page=32
Requesting http://fragments.edmcouncil.org/fibo_1?page=33
Requesting http://fragments.edmcouncil.org/fibo_1?page=32
Requesting http://fragments.edmcouncil.org/fibo_1?page=34
Requesting http://fragments.edmcouncil.org/fibo_1?page=35
Requesting http://fragments.edmcouncil.org/fibo_1?page=33
Requesting http://fragments.edmcouncil.org/fibo_1?page=36
Requesting http://fragments.edmcouncil.org/fibo_1?page=34
Requesting http://fragments.edmcouncil.org/fibo_1?page=35
Requesting http://fragments.edmcouncil.org/fibo_1?page=37
Requesting http://fragments.edmcouncil.org/fibo_1?page=38
Requesting http://fragments.edmcouncil.org/fibo_1?page=36
Requesting http://fragments.edmcouncil.org/fibo_1?page=37
Requesting http://fragments.edmcouncil.org/fibo_1?page=39
Requesting http://fragments.edmcouncil.org/fibo_1?page=40
Requesting http://fragments.edmcouncil.org/fibo_1?page=38
Requesting http://fragments.edmcouncil.org/fibo_1?page=39
Requesting http://fragments.edmcouncil.org/fibo_1?page=41
Requesting http://fragments.edmcouncil.org/fibo_1?page=40
Requesting http://fragments.edmcouncil.org/fibo_1?page=42
Requesting http://fragments.edmcouncil.org/fibo_1?page=41
Requesting http://fragments.edmcouncil.org/fibo_1?page=43
Requesting http://fragments.edmcouncil.org/fibo_1?page=44
Requesting http://fragments.edmcouncil.org/fibo_1?page=42
Requesting http://fragments.edmcouncil.org/fibo_1?page=45
Requesting http://fragments.edmcouncil.org/fibo_1?page=43
Requesting http://fragments.edmcouncil.org/fibo_1?page=46
Requesting http://fragments.edmcouncil.org/fibo_1?page=44
Requesting http://fragments.edmcouncil.org/fibo_1?page=45
Requesting http://fragments.edmcouncil.org/fibo_1?page=47
Requesting http://fragments.edmcouncil.org/fibo_1?page=48
Requesting http://fragments.edmcouncil.org/fibo_1?page=46
Requesting http://fragments.edmcouncil.org/fibo_1?page=47
Requesting http://fragments.edmcouncil.org/fibo_1?page=49
Requesting http://fragments.edmcouncil.org/fibo_1?page=48
Requesting http://fragments.edmcouncil.org/fibo_1?page=50
Requesting http://fragments.edmcouncil.org/fibo_1?page=51
Requesting http://fragments.edmcouncil.org/fibo_1?page=49
Requesting http://fragments.edmcouncil.org/fibo_1?page=50
Requesting http://fragments.edmcouncil.org/fibo_1?page=52
Requesting http://fragments.edmcouncil.org/fibo_1?page=53
Requesting http://fragments.edmcouncil.org/fibo_1?page=51
Requesting http://fragments.edmcouncil.org/fibo_1?page=52
Requesting http://fragments.edmcouncil.org/fibo_1?page=54
Requesting http://fragments.edmcouncil.org/fibo_1?page=53
Requesting http://fragments.edmcouncil.org/fibo_1?page=54
Requesting http://fragments.edmcouncil.org/fibo_1?page=55
Requesting http://fragments.edmcouncil.org/fibo_1?page=55
Requesting http://fragments.edmcouncil.org/fibo_1?page=56
Requesting http://fragments.edmcouncil.org/fibo_1?page=57
Requesting http://fragments.edmcouncil.org/fibo_1?page=56
Requesting http://fragments.edmcouncil.org/fibo_1?page=58
Requesting http://fragments.edmcouncil.org/fibo_1?page=57
Requesting http://fragments.edmcouncil.org/fibo_1?page=59
Requesting http://fragments.edmcouncil.org/fibo_1?page=58
Requesting http://fragments.edmcouncil.org/fibo_1?page=59
Requesting http://fragments.edmcouncil.org/fibo_1?page=60
Requesting http://fragments.edmcouncil.org/fibo_1?page=61
Requesting http://fragments.edmcouncil.org/fibo_1?page=60
Requesting http://fragments.edmcouncil.org/fibo_1?page=61
Requesting http://fragments.edmcouncil.org/fibo_1?page=62
Requesting http://fragments.edmcouncil.org/fibo_1?page=62
Requesting http://fragments.edmcouncil.org/fibo_1?page=63
Requesting http://fragments.edmcouncil.org/fibo_1?page=63
Requesting http://fragments.edmcouncil.org/fibo_1?page=64
Requesting http://fragments.edmcouncil.org/fibo_1?page=65
Requesting http://fragments.edmcouncil.org/fibo_1?page=64
Requesting http://fragments.edmcouncil.org/fibo_1?page=66
Requesting http://fragments.edmcouncil.org/fibo_1?page=65
Requesting http://fragments.edmcouncil.org/fibo_1?page=66
Requesting http://fragments.edmcouncil.org/fibo_1?page=67
Requesting http://fragments.edmcouncil.org/fibo_1?page=68
Requesting http://fragments.edmcouncil.org/fibo_1?page=67
Requesting http://fragments.edmcouncil.org/fibo_1?page=68
Requesting http://fragments.edmcouncil.org/fibo_1?page=69
Requesting http://fragments.edmcouncil.org/fibo_1?page=69
Requesting http://fragments.edmcouncil.org/fibo_1?page=70
Requesting http://fragments.edmcouncil.org/fibo_1?page=70
Requesting http://fragments.edmcouncil.org/fibo_1?page=71

**Comment by RubenVerborgh** [comment]
The problem is that your datasource exposes triples in the non-default graph, which is not supported by the current client (but is supported in a fork). The client is going through all pages to find sufficient triples in the default graph, which it never does.

Note how `curl -H 'Accept: application/n-quads' 'http://fragments.edmcouncil.org/fibo_1'` does not contain a single triple in the default graph.

**Comment by obkhan** [comment]
Interesting, appreciate the quick response!!!!  How could I change it to the default graph instead? 
I'm confused as I did not specify a separate graph, and checked the nquads file itself and the graph is set to "."
Admittedly, I don't totally understand the output of the curl but I did see this:
<http://fragments.edmcouncil.org/fibo_1> <http://www.w3.org/ns/hydra/core#totalItems> "23852"^^<http://www.w3.org/2001/XMLSchema#integer> <http://fragments.edmcouncil.org/fibo_1#metadata>.

I'm using the below for the config file ? Would turning on memento have anything to do with this? I was able to execute the curl command and saw the results

{
    "title": "fragments.edmcouncil.org",
    "port": 80,
    "workers": 2,
    "datasources": {
        "edmcouncil-sparql": {
            "title": "EDM Council FIBO (Stardog) ",
            "type": "SparqlDatasource",
            "description": "Financial Industry Business Ontology - Stardog back-end",
            "settings": {
                "endpoint": "http://stardog.edmcouncil.org/fibo-fragments/query"
            }
        },
        "dbpedia-sparql": {
            "title": "DBpedia 3.9 (Virtuoso)",
            "type": "SparqlDatasource",
            "description": "DBpedia 3.9 with a Virtuoso back-end",
            "settings": {
                "endpoint": "http://dbpedia.restdesc.org/",
                "defaultGraph": "http://dbpedia.org"
            }
        },
        "fibo_1": {
            "title": "FIBO 1",
            "description": "1",
            "type": "TurtleDatasource",
            "settings": {
                "file": "/var/www/fragments.edmcouncil.org/assets/fibo/1.nq"
            },
            "memento": {
                "interval": ["2014-09-15T11:59:59Z", "2015-04-15T00:00:00Z"]
            }
        },
        "fibo_2": {
            "title": "FIBO 2",
            "description": "2",
            "type": "TurtleDatasource",
            "settings": {
                "file": "/var/www/fragments.edmcouncil.org/assets/fibo/2.nq"
            },
            "memento": {
                "interval": ["2015-04-15T00:00:01Z","2016-04-15T00:00:01Z"]
            }
        }
    },

    "timegates": {
        "baseURL": "/timegate/",
        "mementos": {
            "fibo": {
                "versions": [
                    "fibo_1",
                    "fibo_2"
                ]
            }
        }
    },

    "prefixes": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "dc": "http://purl.org/dc/terms/",
        "foaf": "http://xmlns.com/foaf/0.1/",
        "dbpedia": "http://dbpedia.org/resource/",
        "dbpedia-owl": "http://dbpedia.org/ontology/",
        "dbpprop": "http://dbpedia.org/property/",
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "void": "http://rdfs.org/ns/void#"
    }
}

**Comment by rubensworks** [comment]
@obkhan The current LDF client and server only support triples, i.e., quads in the default graph. So unless you change your dataset to remove all graphs, which will result in data loss, there is no way to query that properly at the moment.

We do however have support for this in a separate branch for the [server](https://github.com/LinkedDataFragments/Server.js/tree/feature-qpf-latest) and the [client](https://github.com/LinkedDataFragments/Client.js/tree/feature-qpf-latest). We intend to release these versions soon. If you want, you can try out these in the meantime at your own risk :-)

**Comment by obkhan** [comment]
Hi - I think I maybe get the obvious now, we would have to use something like riot / rapper to convert the nquads to triples , which would be lossy?
Any guess when to expect the support for nquads will be released? 
If it is far off, what would I need to do for the pre-release versions would the configuration be different?

**Comment by rubensworks** [comment]
If all goes well, we'll release the next version somewhere this month, but no promises there.

You can definitely try the QPF branch yourself, nothing has changed to the configuration files there. Note that for the next release, the configuration files _will_ change slightly, but more information on that will follow.

**Comment by obkhan** [comment]
Hi - just curious when the next release is planned, or should try the QPF branch if it's down the road a bit?
