### ISSUE TITLE
Client process sometimes doesn't terminate

### ISSUE THREAD

**Issue by mielvds** [LinkedDataFragments/Client.js#38]
After executing a query, the query ends (i.e., the resultset is closed), but the process hangs.
At first I thought `fragments.dbpedia.org` ends, but `data.linkeddatafragments.org/dbpedia` doesn’t. But after a second run `fragments.dbpedia.org` also didn't terminate. 
Thus, it seems to be a race condition of some sort and not related to the server.

I'm using node v8.2.1 and the latest master

**Comment by joachimvh** [comment]
Trying to reproduce this, can you give an example of a query where this occurred? Also: did you execute it on fragments.dbpedia.org itself or one of its sub-endpoints?

**Comment by mielvds** [comment]
it is more likely to happen when using `http://fragments.dbpedia.org/en` instead of `http://fragments.dbpedia.org/2016-04/en`

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), where this should not be a problem anymore. If it is, feel free to open a new issue there.
