### ISSUE TITLE
Parsing GRAPH

### ISSUE THREAD

**Issue by ariutta** [LinkedDataFragments/Client.js#4]
I'm assuming the [GRAPH keyword](http://www.w3.org/2001/sw/DataAccess/rq23/#queryDataset) is not yet supported because it doesn't appear in the regex [here](https://github.com/LinkedDataFragments/Client/blob/master/lib/SparqlQueryParser.js#L10), and I'm getting `Error: Could not parse query` when I try running a [query using GRAPH](https://github.com/ariutta/wp-ldf/blob/master/graph.sparql) on this [turtle datasource](https://github.com/ariutta/wp-ldf/blob/master/config-server-local-turtle.json).

Would [this file](https://github.com/LinkedDataFragments/Server/blob/5272b4d823028b6ef60f2ac6687b58e6f6e72603/lib/SparqlDatasource.js#L10) be the place to start for adding support for the GRAPH keyword?

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), where the requested feature is supported.
