### ISSUE TITLE
ERROR: Query execution could not start.

### ISSUE THREAD

**Issue by cutup** [LinkedDataFragments/Client.js#41]
This Error return after execute a query.

~/Client.js# bin/ldf-client http://fragments.dbpedia.org/2015/en queries/union.sparql
ERROR: Query execution could not start.

The query is not yet supported
Object function Object() { [native code] } has no method 'assign'

**Comment by RubenVerborgh** [comment]
Your Node.js version is too old, please use 4.x or up.

**Comment by cutup** [comment]
it works. thanks :-)
