### ISSUE TITLE
Date ranges / intervals 

### ISSUE THREAD

**Issue by akuckartz** [LinkedDataFragments/Client.js#5]
Are there or will there be support for date ranges, such as events between 2012-11-28 and 2014-02-05? In other words: will such filtering be done by the client or by the server (or are both possible)?

If it has not yet been decided: the example interval above could be devided by the client into such fragments:
- 2012-11-28
- 2012-11-29
- 2012-11-30 (and maybe 2012-11-31)
- 2012-12 (whole month)
- 2013 (whole year)
- 2014-01
- 2014-02-01
- 2014-02-02
- 2014-02-03
- 2014-02-04
- 2014-02-05

**Comment by rubensworks** [comment]
This project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica), if you are still interested in this, feel free to create a new issue there.
